name: osu
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  keyboard_actions: "^2.1.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app-icon.png"

flutter:
  uses-material-design: true
